export const EVENTS = {
	DEDUPLICATE_TABS: "vertical-tabs:deduplicate-tabs",
	EPHEMERAL_TABS_INIT: "vertical-tabs:ephemeral-tabs-init",
	EPHEMERAL_TABS_DEINIT: "vertical-tabs:ephemeral-tabs-deinit",
	EPHEMERAL_TABS_UPDATE: "vertical-tabs:ephemeral-tabs-update",
	UPDATE_TOGGLE: "vertical-tabs:update-toggle",
	ENHANCED_KEYBOARD_TAB_SWITCH: "vertical-tabs:enhanced-keyboard-tab-switch",
	RESET_KEYBOARD_TAB_SWITCH: "vertical-tabs:reset-keyboard-tab-switch",
	GROUP_VIEW_CHANGE: "vertical-tabs:group-view-change",
	EPHEMERAL_TOGGLE: "vertical-tabs:ephemeral-toggle",
	ALT_KEY_PRESSED: "vertical-tabs:alt-key-pressed",
	RENDER_TAB_ICON: "vertical-tabs:render-tab-icon",
	RENDER_GROUP_ICON: "vertical-tabs:render-group-icon",
	REQUEST_ICON_REFRESH: "vertical-tabs:request-icon-refresh",
	ON_TAB_MENU: "vertical-tabs:on-tab-menu",
	ON_TABS_MENU: "vertical-tabs:on-tabs-menu",
	ON_GROUP_MENU: "vertical-tabs:on-group-menu",
} as const;
