name: Enhancement
description: I want to suggest an improvement for Vertical Tabs. For new features, please create a new "Idea" discussion in the "Discussions" tab.
labels:
  - enhancement
projects:
  - oxdc/1
body:
- type: checkboxes
  id: checklist
  attributes:
    label: Enhancement Checklist
    options:
      - label: I have searched existing issues and this is not a duplicate
        required: true
      - label: I am reporting a simple enhancement or improvement within Vertical Tabs, not requesting new features or addressing compatibility issues with other plugins
        required: true
      - label: I understand that proposals for new features should be discussed in the ‘Discussions’ tab
        required: true
      - label: I understand that compatibility issues with other plugins should be posted as a 'Compatibility' issue
        required: true
- type: checkboxes
  id: beta-version
  attributes:
    label: Beta Version
    options:
      - label: I am using a beta version of Vertical Tabs
        required: false
- type: input
  id: beta-version-tag
  attributes:
    label: Beta Version Tag (if applicable)
    description: If you checked the beta version box above, please provide the specific beta version tag you are using.
    placeholder: e.g., 0.99.9-beta-20990909
  validations:
    required: false
- type: dropdown
  id: type
  attributes:
    label: Enhancement Type
    description: Please select the type of enhancement you are suggesting.
    options:
      - "--- Select an option ---"
      - "Usability"
      - "Performance"
      - "Accessibility"
      - "Design"
      - "Other"
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Enhancement Description
    description: |-
      Please provide a clear and concise description of the enhancement you are suggesting. What do you want to achieve?
      
      **Note:** If English is not your first language, please consider use ChatGPT or similar AI tools to translate your text.
    placeholder: Describe the enhancement here...
  validations:
    required: true
- type: textarea
  id: motivation
  attributes:
    label: Motivation
    description: |-
      Please explain why this enhancement is important. How does it benefit the users of Vertical Tabs?
      
      The best way to describe this is to show your own use case. What have you tried to do that you couldn't because of the current limitations? Why is this important to you?
    placeholder: Explain the motivation here...
  validations:
    required: true
- type: textarea
  id: alternatives
  attributes:
    label: Alternatives (Optional)
    description: If you have considered any alternative solutions or workarounds, please describe them here.
    placeholder: Describe alternatives here...
- type: textarea
  id: additional-info
  attributes:
    label: Additional Information (Optional)
    description: Please provide any additional information that you think would be helpful for the maintainers to understand your suggestion. You can include screenshots, mockups, or any other relevant information.
    placeholder: Provide additional information here...
