name: Beta Build & Hash

on:
  workflow_dispatch:
  repository_dispatch:
    types: [beta-build]
  push:
    tags:
      - "*-beta-*"

jobs:
  build-beta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout beta branch
        uses: actions/checkout@v4
        with:
          ref: beta

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build beta version
        run: bun run build:beta

      - name: Create release
        uses: akkuman/gitea-release-action@v1
        with:
          files: |-
            dist/**
          prerelease: true
          sha256sum: true
