name: Release

on:
  push:
    tags:
      - "*"
      - "!*-beta-*"

jobs:
  release:
    uses: obsidianmd/obsidian-workflows/.github/workflows/release.yml@v1
    permissions:
      contents: write
      id-token: write
      attestations: write
